version: '2.1'
services:
  go1.22:
    build:
      context: .
      dockerfile: Dockerfile
    image: dc_golang:1.25
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    extra_hosts:
      - "pc_rabbit:172.18.0.253"
      - "pc_redis:172.18.0.254"
      - "pjp-be-transaction-module:172.18.0.1"
      - "pjp-be-settlementpg-module:172.18.0.1"
      - "pjp-be-merchantpg-module:172.18.0.1"
      - "pjp-be-config-module:172.18.0.1"
      - "pjp-be-messaging-module:172.18.0.1"
      - "pjp-be-dashboard-module:172.18.0.1"
      - "pjp-be-withdrawal-module:172.18.0.1"
    environment:
      TZ: "Asia/Jakarta"
    mem_limit: 1g
    healthcheck:
      disable: true
    volumes:
      - ./:/docker/
      - gopkg:/go/pkg/
    entrypoint: "/docker/docker/golang/run.sh"
