version: '2.1'
services:
  #######################################
  # GO Services
  #######################################
  movebe:
    extends:
      file: common-services.yml
      service: go1.19
    container_name: go_movebe
    external_links:
      - dev_mariadb:mariadb
    environment:
      VIRTUAL_HOST: "movebe.vm"
      VIRTUAL_PORT: "80"
      ENV: "dev"
    mem_limit: 200m
    networks:
      default:
        ipv4_address: 172.18.0.121
    volumes:
      - /home/nath/go/src/wwt_go_movebe:/go/src/wwt_go_movebe
    working_dir: "/go/src/wwt_go_movebe"

  codigribe:
    image: go_codigribe
    extra_hosts:
      - "mariadb:172.18.0.4"
    container_name: go_codigribe
    environment:
      VIRTUAL_HOST: "codigribe.vm"
      VIRTUAL_PORT: "80"
      ENV: "dev"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - /home/nath/go/src/wwt_go_codigribe:/app
    network_mode: "host"

  wjngamebe:
    image: go_wjngamebe
    extra_hosts:
      - "mariadb:172.18.0.4"
    container_name: go_wjngamebe
    environment:
      VIRTUAL_HOST: "wjngamebe.vm"
      VIRTUAL_PORT: "80"
      ENV: "dev"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - /home/nath/go/src/wwt_go_wjn_game:/app
    network_mode: "host"

#######################################
# Volumes
#######################################
volumes:
  gosrc:
    driver: local
    driver_opts:
      type: bind
      device: /home/nath/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      type: bind
      device: /home/nath/go/pkg
      o: bind

networks:
  default:
    external:
      name: dev
